name: verify

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

env:
  HOME: /var/lib/gitea-runner
  SSH_OPTS: >-
    -i /var/lib/gitea-runner/.ssh/id_ed25519
    -o StrictHostKeyChecking=accept-new
    -o UserKnownHostsFile=/var/lib/gitea-runner/known_hosts

concurrency:
  group: verify
  cancel-in-progress: false

jobs:
  verify:
    runs-on: native
    steps:
      - uses: actions/checkout@v4

      - name: VERIFYING
        run: nix --extra-experimental-features "nix-command flakes" run .#verify
