exec-once = noctalia-shell

# Noctalia keybinds
# Open app launcher on Super key (press and release)
bindr = SUPER, SUPER_L, exec, noctalia-shell ipc call launcher toggle
# Control center
bind = SUPER, A, exec, noctalia-shell ipc call controlCenter toggle
# Session menu (logout, reboot, shutdown...)
bind = SUPER, X, exec, noctalia-shell ipc call sessionMenu toggle
